#UserModule URL's
post_url = https://petstore.swagger.io/v2/user
get_url = https://petstore.swagger.io/v2/user/{username}
update_url = https://petstore.swagger.io/v2/user/{username}
delete_url = https://petstore.swagger.io/v2/user/{username}

#PetModule URL's
post_peturl = https://petstore.swagger.io/v2/pet
get_peturl = https://petstore.swagger.io/v2/pet/{petId}
update_peturl = https://petstore.swagger.io/v2/pet
delete_peturl = https://petstore.swagger.io/v2/pet/{petId}